services:
  postgres:
    image: postgres:18
    container_name: dj_ai-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: linux4ever
      POSTGRES_DB: dj-ai
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c max_connections=200
      -c shared_buffers=256MB

volumes:
  postgres-data: