version: '3.8'
networks:
  djai-net:

services:
  postgres:
    image: postgres:18
    container_name: dj_ai-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: linux4ever
      POSTGRES_DB: dj-ai
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c max_connections=200
      -c shared_buffers=256MB
    networks:
      - djai-net

  redis:
    image: redis:7.2-alpine
    container_name: djai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - djai-net

  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    container_name: djai-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ../api/.env
    environment:
      - PYTHONPATH=/workspace
    working_dir: /workspace/api
    depends_on:
      - postgres
      - redis
    volumes:
      - ../:/workspace
    command: ["python", "main.py"]
    networks:
      - djai-net



  frontend:
    build:
      context: ../frontend
    container_name: djai-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    command: ["npm", "start"]
    networks:
      - djai-net

volumes:
  redis_data:
  postgres-data:
